### ISSUE TITLE
Add a working emulator to the repo, in place of the example project

### ISSUE THREAD

**Issue by adam-becker** [libretro-rs/libretro-rs#22]
The example project is neat, but I think having a concrete example would be better. I have a CHIP-8 emulator to offer up for this purpose, it's simple and uses more functionality than the current example. Thoughts?

/cc @InquisitiveCoder

**Comment by InquisitiveCoder** [comment]
I agree! It'd be really nice to see an example that uses more of the API. An emulator sounds ideal. I have a content-less toy core that sets up OpenGL and lets you move a rectangle, but yours sounds better.

**Comment by adam-becker** [comment]
Done in a23aa432f5350968226ed29c8ac245565c3f480d.
