### ISSUE TITLE
Can't call RetroEnvironment::set_raw

### ISSUE THREAD

**Issue by InquisitiveCoder** [libretro-rs/libretro-rs#5]
[Commit 90b72a8 ("Factor out a sys crate")](https://github.com/libretro-rs/libretro-rs/commit/90b72a86acdc04063efde608b6638b7ccd3db043)  changed the first argument for `RetroEnvironment::set_raw` from `&self` to `&mut self`. However, `RetroCore` still receives non-`mut` references to `RetroEnvironment` in all of its functions. As a result, it's not possible to call `set_raw` any more.

**Comment by adam-becker** [comment]
I should really test these changes alongside my own emulator 😉. Do you have a use case for `set_raw` at the moment, or is this just some API roughness that you noticed?

**Comment by InquisitiveCoder** [comment]
I'm currently using `set_raw` for `RETRO_ENVIRONMENT_GET_LOG_INTERFACE` and `RETRO_ENVIRONMENT_SET_HW_RENDER`. I'd like to add proper support for both those features in `libretro-rs`, but until then I need to use `set_raw`.

I've already fixed this locally but I think I'll wait for my current PR to be merged before I rebase my branch and open a new PR for this.

**Comment by adam-becker** [comment]
Closed via #8
