### ISSUE TITLE
Can't call RetroRuntime::is_joypad_button_pressed

### ISSUE THREAD

**Issue by InquisitiveCoder** [libretro-rs/libretro-rs#6]
[Commit 9b4c3f0 ("various cleanups and improvements")](https://github.com/libretro-rs/libretro-rs/commit/9b4c3f0a0f2d0af6e4a18b6f5f0d1064f555626e) changed the first argument of `RetroRuntime::is_joypad_button_pressed` from `u32` to `RetroDevicePort`, but `RetroDevicePort` doesn't have a public constructor.

**Comment by adam-becker** [comment]
Emulators don't need to query for buttons though.. right? 😅
