### ISSUE TITLE
Support gameless cores

### ISSUE THREAD

**Issue by InquisitiveCoder** [libretro-rs/libretro-rs#9]
When the environment callback is called with `RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME` is set to `true`, `retro_load_game()` will be called with `NULL` rather than a pointer to a `retro_game_info`. However, this currently can't be used in practice since:
* `libretro_core!` and `RetroInstance::on_load_game` use `&retro_game_info` as the type of its argument.
* `RetroCore` uses `RetroGame` as the type of its argument.
Neither of these types are allowed to be null.

At a minimum `libretro_core` and `on_load_game` need a different type to accommodate the `NULL` value. As for `RetroCore`, I'm not sure if you'd prefer changing the argument to `Option<RetroGame>` or having a separate trait (e.g. `NoGameRetroCore`) that doesn't have the `RetroGame` argument at all.

My core is a game rather than an emulator and I won't be loading any of the game data from an external file so this use case is directly relevant to me. In particular, not having this forces me to create a 0 byte "rom" just so RetroArch will load my core.

**Comment by adam-becker** [comment]
I think we just need to detect the null pointer and map that to `RetroGame::None`?

**Comment by InquisitiveCoder** [comment]
Ah, you're right! I hadn't noticed that `RetroGame` is an `enum`.
